### Test Hello
GET http://localhost:3000/test/hello

### List bank accounts
GET http://localhost:3000/bank-accounts

### Register bank account
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
    "account_number": "1111-1",
    "owner_name": "John Doe"
}

### Get bank account by id
@bank_acount_id = 67d88a4a-cc19-4245-8e1a-4ef3e617c94f
GET http://localhost:3000/bank-accounts/{{bank_acount_id}}

### List account pix keys
GET http://localhost:3000/bank-accounts/{{bank_acount_id}}/pix-keys

### Register account pix key
POST http://localhost:3000/bank-accounts/{{bank_acount_id}}/pix-keys
Content-Type: application/json

{
    "kind": "email",
    "key": "usertest1@email.com"
}

### List account transactions
GET http://localhost:3000/bank-accounts/{{bank_acount_id}}/transactions

### Create a new transaction
POST http://localhost:3000/bank-accounts/{{bank_acount_id}}/transactions
Content-Type: application/json

{
    "pix_key_key": "usertest1@email.com",
    "pix_key_kind": "email",
    "description": "Test transaction",
    "amount": 10.00
}
